name: Docker Multi-Architecture Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Build Cargo
        run: cargo build --release && mv target/release/sponsorblock-mirror .
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          config: .github/buildkitd.toml
          version: latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.ci
          platforms: "linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8"
          push: false
          tags: 1337kavin/sponsorblock-mirror:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
